/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DayData = IDL.Record({
  'callOI' : IDL.Float64,
  'change' : IDL.Float64,
  'expiry' : IDL.Text,
  'price' : IDL.Float64,
  'putOI' : IDL.Float64,
});
export const MarketDynamics = IDL.Record({
  'underlying' : DayData,
  'put_oi_time_series' : IDL.Vec(IDL.Float64),
  'call_oi_time_series' : IDL.Vec(IDL.Float64),
  'change_time_series' : IDL.Vec(IDL.Float64),
  'expiry' : IDL.Text,
  'price_time_series' : IDL.Vec(IDL.Float64),
});
export const Signal = IDL.Record({
  'action' : IDL.Text,
  'urgency' : IDL.Text,
  'message' : IDL.Text,
  'expiry' : IDL.Text,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'calculateTradeSignals' : IDL.Func([MarketDynamics], [IDL.Vec(Signal)], []),
  'fetchATMStrikes' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Nat)], []),
  'fetchATMVolume' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
  'fetchHistoricalMarketData' : IDL.Func(
      [IDL.Text, IDL.Text],
      [MarketDynamics],
      [],
    ),
  'fetchKeyLevels' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Nat)], []),
  'fetchMarketDynamics' : IDL.Func([IDL.Text], [MarketDynamics], []),
  'fetchPCR' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
  'fetchPCRStrength' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'fetchPCRVolume' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
  'fetchSkewIndicator' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [],
    ),
  'fetchSustainedStrength' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DayData = IDL.Record({
    'callOI' : IDL.Float64,
    'change' : IDL.Float64,
    'expiry' : IDL.Text,
    'price' : IDL.Float64,
    'putOI' : IDL.Float64,
  });
  const MarketDynamics = IDL.Record({
    'underlying' : DayData,
    'put_oi_time_series' : IDL.Vec(IDL.Float64),
    'call_oi_time_series' : IDL.Vec(IDL.Float64),
    'change_time_series' : IDL.Vec(IDL.Float64),
    'expiry' : IDL.Text,
    'price_time_series' : IDL.Vec(IDL.Float64),
  });
  const Signal = IDL.Record({
    'action' : IDL.Text,
    'urgency' : IDL.Text,
    'message' : IDL.Text,
    'expiry' : IDL.Text,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'calculateTradeSignals' : IDL.Func([MarketDynamics], [IDL.Vec(Signal)], []),
    'fetchATMStrikes' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Nat)], []),
    'fetchATMVolume' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
    'fetchHistoricalMarketData' : IDL.Func(
        [IDL.Text, IDL.Text],
        [MarketDynamics],
        [],
      ),
    'fetchKeyLevels' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Nat)], []),
    'fetchMarketDynamics' : IDL.Func([IDL.Text], [MarketDynamics], []),
    'fetchPCR' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
    'fetchPCRStrength' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'fetchPCRVolume' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], []),
    'fetchSkewIndicator' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
      ),
    'fetchSustainedStrength' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };