/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DayData {
  'callOI' : number,
  'change' : number,
  'expiry' : string,
  'price' : number,
  'putOI' : number,
}
export interface MarketDynamics {
  'underlying' : DayData,
  'put_oi_time_series' : Array<number>,
  'call_oi_time_series' : Array<number>,
  'change_time_series' : Array<number>,
  'expiry' : string,
  'price_time_series' : Array<number>,
}
export interface Signal {
  'action' : string,
  'urgency' : string,
  'message' : string,
  'expiry' : string,
  'price' : number,
  'symbol' : string,
}
export interface _SERVICE {
  'calculateTradeSignals' : ActorMethod<[MarketDynamics], Array<Signal>>,
  'fetchATMStrikes' : ActorMethod<[string, string], Array<bigint>>,
  'fetchATMVolume' : ActorMethod<[string, string], number>,
  'fetchHistoricalMarketData' : ActorMethod<[string, string], MarketDynamics>,
  'fetchKeyLevels' : ActorMethod<[string, string], Array<bigint>>,
  'fetchMarketDynamics' : ActorMethod<[string], MarketDynamics>,
  'fetchPCR' : ActorMethod<[string, string], number>,
  'fetchPCRStrength' : ActorMethod<[string, string], string>,
  'fetchPCRVolume' : ActorMethod<[string, string], number>,
  'fetchSkewIndicator' : ActorMethod<
    [string, string],
    [number, number, number]
  >,
  'fetchSustainedStrength' : ActorMethod<[string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];