/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    action: string;
    urgency: string;
    message: string;
    expiry: string;
    price: number;
    symbol: string;
}
export interface MarketDynamics {
    underlying: DayData;
    put_oi_time_series: Array<number>;
    call_oi_time_series: Array<number>;
    change_time_series: Array<number>;
    expiry: string;
    price_time_series: Array<number>;
}
export interface DayData {
    callOI: number;
    change: number;
    expiry: string;
    price: number;
    putOI: number;
}
export interface backendInterface {
    calculateTradeSignals(marketDynamics: MarketDynamics): Promise<Array<Signal>>;
    fetchATMStrikes(_symbol: string, _expiry: string): Promise<Array<bigint>>;
    fetchATMVolume(_symbol: string, _expiry: string): Promise<number>;
    fetchHistoricalMarketData(_symbol: string, expiry: string): Promise<MarketDynamics>;
    fetchKeyLevels(_symbol: string, _expiry: string): Promise<Array<bigint>>;
    fetchMarketDynamics(_symbol: string): Promise<MarketDynamics>;
    fetchPCR(_symbol: string, _expiry: string): Promise<number>;
    fetchPCRStrength(_symbol: string, _expiry: string): Promise<string>;
    fetchPCRVolume(_symbol: string, _expiry: string): Promise<number>;
    fetchSkewIndicator(_symbol: string, _expiry: string): Promise<[number, number, number]>;
    fetchSustainedStrength(_symbol: string, _expiry: string): Promise<string>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateTradeSignals(arg0: MarketDynamics): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTradeSignals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTradeSignals(arg0);
            return result;
        }
    }
    async fetchATMStrikes(arg0: string, arg1: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchATMStrikes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchATMStrikes(arg0, arg1);
            return result;
        }
    }
    async fetchATMVolume(arg0: string, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchATMVolume(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchATMVolume(arg0, arg1);
            return result;
        }
    }
    async fetchHistoricalMarketData(arg0: string, arg1: string): Promise<MarketDynamics> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchHistoricalMarketData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchHistoricalMarketData(arg0, arg1);
            return result;
        }
    }
    async fetchKeyLevels(arg0: string, arg1: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchKeyLevels(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchKeyLevels(arg0, arg1);
            return result;
        }
    }
    async fetchMarketDynamics(arg0: string): Promise<MarketDynamics> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchMarketDynamics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchMarketDynamics(arg0);
            return result;
        }
    }
    async fetchPCR(arg0: string, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchPCR(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchPCR(arg0, arg1);
            return result;
        }
    }
    async fetchPCRStrength(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchPCRStrength(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchPCRStrength(arg0, arg1);
            return result;
        }
    }
    async fetchPCRVolume(arg0: string, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchPCRVolume(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchPCRVolume(arg0, arg1);
            return result;
        }
    }
    async fetchSkewIndicator(arg0: string, arg1: string): Promise<[number, number, number]> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSkewIndicator(arg0, arg1);
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSkewIndicator(arg0, arg1);
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async fetchSustainedStrength(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSustainedStrength(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSustainedStrength(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
